# Generated by Django 4.1.5 on 2023-01-07 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=225)),
                ('model', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='ad_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=255, verbose_name='Марка')),
                ('mod', models.CharField(max_length=255, verbose_name='Модель')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год выпуска')),
                ('millage', models.PositiveIntegerField(verbose_name='Пробег')),
                ('owners', models.PositiveSmallIntegerField(verbose_name='Кол-во владельцев')),
                ('images', models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Фото')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
