# Generated by Django 4.1.4 on 2022-12-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ad_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=255, null=True, verbose_name='Марка')),
                ('mod', models.CharField(max_length=255, null=True, verbose_name='Модель')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год выпуска')),
                ('millage', models.PositiveIntegerField(verbose_name='Пробег')),
                ('owners', models.PositiveSmallIntegerField(verbose_name='Количество владельцев')),
                ('images', models.ImageField(upload_to='photos', verbose_name='Фото')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
            ],
        ),
    ]
