# Generated by Django 4.1.4 on 2022-12-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad_car',
            name='images',
            field=models.ImageField(null=True, upload_to='photos', verbose_name='Фото'),
        ),
    ]
