# Generated by Django 4.1.4 on 2022-12-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_ad_car_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad_car',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Фото'),
        ),
    ]
