# Generated by Django 4.1.4 on 2022-12-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_ad_car_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad_car',
            name='owners',
            field=models.PositiveSmallIntegerField(verbose_name='Кол-во владельцев'),
        ),
    ]
