# Generated by Django 4.1.4 on 2023-01-04 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0005_alter_ad_car_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad_car',
            name='mark',
            field=models.CharField(default=1, max_length=255, verbose_name='Марка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad_car',
            name='mod',
            field=models.CharField(max_length=255, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='ad_car',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
